### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by ghost** [ba-sz-at/origamieditor3d#1]
How I can make translating for Origami Editor 3D?

**Comment by bagyoni** [comment]
Use Eclipse with the [ResourceBundle Editor](https://marketplace.eclipse.org/content/resourcebundle-editor) plug-in.
The English language file is [src/language_en_properties](https://github.com/ba-sz-at/origamieditor3d/blob/master/src/language_en.properties). Right click that file in the Package Explorer and select **Open With > ResourceBundle Editor**. Click the **New** tab at the bottom to add a new locale.
You should also edit the locales.properties file to see the new language appear in the Languages menu.
